version: '3.7'
services:

  vzdb:
    image: docker.orientge.cn:5000/oge/vzdb:2.72.1
    ports:
      - "${vzdb_port}:22235/tcp"
      - "${vzevt_port}:22136/tcp"
    # environment:
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/oge/oge_data/vzdb-${vzdb_port}/model/:/oge/vzdb/model"
      - "/home/oge/oge_data/vzdb-${vzdb_port}/cache/:/oge/vzdb/cache"
      - "/home/oge/oge_data/vzdb-${vzdb_port}/data/:/oge/vzdb/data"
      - "/home/oge/oge_logs/vzdb-${vzdb_port}/:/oge/vzdb/log"
    container_name: vzdb-${vzdb_name}

networks:
  default:
    name: ${networks_name}