version: "3.7"
service:
    rtdb:
        image: oge/kdm-rtdb-vzdb:1.2.0
        ports:
            - ${reg_server}:regHost
            - ${rtdb_server}:rtdbHost
        environment:
            spring.application.name: kdm-rdp-rtdb-vzdb-${server_name}
            spring.profiles.active: reg_consul,alias_none
            kdm.reg.host: regHost
            kdm.rtdb.host: rtdbHost
            kdm.rtdb.port: ${rtdb_port}
            kdm.rtdb.username: ${rtdb_username}
            kdm.rtdb.password: ${rtdb_password}
            kdm.rtdb.rule: ${rtdb_rule}
        volumes:
            - /home/oge/oge_logs/kdm-rdp-rtdb-vzdb-${server_port}/:/oge/log
            - /etc/localtime:/etc/localtime:ro
        container_name: kdm-rdp-rtdb-vzdb-${server_port}